GET http://localhost:5000/users/

###
POST http://localhost:5000/users/ 
Content-Type: application/json

{
    "name" : "M. Randi",
    "email" : "randi@gmail.com",
    "password" : "123456",
    "confPassword" : "123456"
}